apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pets
      service: web
  template:
    metadata:
      labels:
        app: pets
        service: web
    spec:
      containers:
        - image: alexgravx/pet-store-web:1.0
          name: web
          ports:
            - containerPort: 3000
              protocol: TCP
