apiVersion: v1
kind: Service
metadata:
  name: web
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: gravlax
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: tripmeal
    service: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tripmeal
      service: web
  template:
    metadata:
      labels:
        app: tripmeal
        service: web
    spec:
      containers:
      - image: tripmealreggravlax.azurecr.io/tripmeal-web:latest
        name: web
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: DATABASE_NAME
          valueFrom:
              configMapKeyRef:
                name: tripmeal-env
                key: DATABASE_NAME
        - name: DATABASE_USER
          valueFrom:
              secretKeyRef:
                name: tripmeal-secret
                key: DATABASE_USER
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: tripmeal-secret
                key: MYSQL_ROOT_PASSWORD
        - name: DATABASE_HOST
          valueFrom:
              configMapKeyRef:
                name: tripmeal-env
                key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
              configMapKeyRef:
                name: tripmeal-env
                key: DATABASE_PORT
        - name: TRIPMEAL_KEY
          valueFrom:
              secretKeyRef:
                name: tripmeal-secret
                key: TRIPMEAL_KEY
        - name: SERVER_PORT
          valueFrom:
              configMapKeyRef:
                name: tripmeal-env
                key: SERVER_PORT
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: tripmeal
      service: db
  serviceName: db
  template:
    metadata:
      labels:
        app: tripmeal
        service: db
    spec:
      containers:
        - image: tripmealreggravlax.azurecr.io/tripmeal-database:latest
          name: db
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: tripmeal-data
          env:
            - name: DATABASE_NAME
              valueFrom:
                  configMapKeyRef:
                    name: tripmeal-env
                    key: DATABASE_NAME
            - name: DATABASE_USER
              valueFrom:
                  secretKeyRef:
                    name: tripmeal-secret
                    key: DATABASE_USER
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: tripmeal-secret
                    key: MYSQL_ROOT_PASSWORD
            - name: DATABASE_HOST
              valueFrom:
                  configMapKeyRef:
                    name: tripmeal-env
                    key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                  configMapKeyRef:
                    name: tripmeal-env
                    key: DATABASE_PORT
  volumeClaimTemplates:
    - metadata:
        name: tripmeal-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: tripmeal
    service: db
